version: '3'
services:
  c-etherpad-lite:
    image: tvelocity/etherpad-lite
    environment:
      - "ETHERPAD_TITLE=Open State Foundation Etherpad Lite"
      - "ETHERPAD_PORT=80"
      - "ETHERPAD_ADMIN_PASSWORD=<YOUR_ETHERPAD_ADMIN_PASSWORD>"
      - "ETHERPAD_DB_HOST=c-etherpad-lite-mysql"
      - "ETHERPAD_DB_PASSWORD=<YOUR_ETHERPAD_DB_PASSWORD>"
    restart: always
    networks:
      - nginx-load-balancer
      - etherpad-lite
  c-etherpad-lite-mysql:
    image: mysql
    # This root password will be overwritten with the password used in
    # the backup that will be restored from a .sql file in the
    # docker-entrypoint-initdb.d directory. When starting a totally new
    # instance look in `docker-compose logs` for the line with
    # 'GENERATED ROOT PASSWORD:' to find the password and use it in
    # 'ETHERPAD_DB_PASSWORD' above and in backup.sh.
    environment:
      - "MYSQL_RANDOM_ROOT_PASSWORD=yes"
    restart: always
    volumes:
      - etherpad-lite-volume:/var/lib/mysql
      - "./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    networks:
      - etherpad-lite
volumes:
  etherpad-lite-volume:
networks:
  etherpad-lite:
  nginx-load-balancer:
    external:
      name: docker_nginx-load-balancer
